# Copyright 2026 Gautham Anil
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
slam.launch.py
==============
Online async SLAM with slam_toolbox for the Coco robot.

In Jazzy, async_slam_toolbox_node is a managed LifecycleNode: it must be
configured then activated before it subscribes to /scan. This launch does
that automatically via lifecycle transition events (the same pattern as
slam_toolbox's own online_async_launch.py).

Run the simulation first, then this, then drive the robot to build the map:

  ros2 launch gazebo_models full_world_robo.launch.py
  ros2 launch gazebo_models slam.launch.py
  ros2 run gazebo_models map_drive.py

Save the finished map. Write it into the *source* tree so it survives a
rebuild — the installed share directory is regenerated by colcon:

  ros2 run nav2_map_server map_saver_cli -f <path-to-repo>/gazebo_models/maps/coco_world \
      --ros-args -p use_sim_time:=true
"""

import os

from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, EmitEvent, LogInfo, RegisterEventHandler
from launch.events import matches_action
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import LifecycleNode
from launch_ros.event_handlers import OnStateTransition
from launch_ros.events.lifecycle import ChangeState
from lifecycle_msgs.msg import Transition


def generate_launch_description():
    pkg_share = get_package_share_directory('gazebo_models')
    slam_params = os.path.join(pkg_share, 'config', 'slam_params.yaml')
    use_sim_time = LaunchConfiguration('use_sim_time')

    slam_node = LifecycleNode(
        package='slam_toolbox',
        executable='async_slam_toolbox_node',
        name='slam_toolbox',
        namespace='',
        output='screen',
        parameters=[
            slam_params,
            {'use_sim_time': use_sim_time, 'use_lifecycle_manager': False},
        ],
    )

    configure_event = EmitEvent(event=ChangeState(
        lifecycle_node_matcher=matches_action(slam_node),
        transition_id=Transition.TRANSITION_CONFIGURE,
    ))

    activate_event = RegisterEventHandler(OnStateTransition(
        target_lifecycle_node=slam_node,
        start_state='configuring',
        goal_state='inactive',
        entities=[
            LogInfo(msg='[slam.launch] slam_toolbox configured -> activating'),
            EmitEvent(event=ChangeState(
                lifecycle_node_matcher=matches_action(slam_node),
                transition_id=Transition.TRANSITION_ACTIVATE,
            )),
        ],
    ))

    return LaunchDescription([
        DeclareLaunchArgument('use_sim_time', default_value='true'),
        slam_node,
        configure_event,
        activate_event,
    ])
