# Teleop Arm Configuration
teleop_arm:
  ros__parameters:
    step_size: 0.1
    shoulder_min: -3.839724354
    shoulder_max: 0.0
    elbow_min: -1.5
    elbow_max: 0.0
    grip_left_min: -0.3
    grip_left_max: 1.047
    grip_right_min: -1.047
    grip_right_max: 0.3
    home_shoulder: 0.0
    home_elbow: 0.0
    home_grip_left: 0.0
    home_grip_right: 0.0
    publish_rate: 50.0
