#!/usr/bin/env python3
"""Condense raw container evidence into the committed, machine-readable set.

usage: condense_evidence.py INDEX_JSON OUT_DIR

INDEX_JSON names every raw run and what kind it is; paths in it are
relative to its "root". The raw runs (build logs, container logs, ROS
logs, JUnit) stay outside the repository; what lands in OUT_DIR is
derived from them by this script and nothing else, so the committed
numbers can be regenerated by anyone holding the raw evidence.

Kinds: build, validate, host_tests, contention, repeat, platform,
boot_probe, regression, determinism, failure, environment.
"""
import csv
import glob
import json
import os
import re
import sys


def rj(path, default=None):
    try:
        return json.load(open(path))
    except Exception:  # noqa: BLE001
        return default


def kv(path):
    out = {}
    if os.path.exists(path):
        for line in open(path):
            for m in re.finditer(r'(\w+)=(\S+)', line):
                out[m.group(1)] = m.group(2)
    return out


def build(d):
    m = rj(os.path.join(d, 'build-meta.json'))
    if m is None:                                   # measure_build.sh layout
        r = rj(os.path.join(d, 'result.json'), {})
        s = rj(os.path.join(d, 'steps.json'), [])
        m = {'tag': r.get('tag'), 'rc': r.get('rc'),
             'wall_seconds': r.get('seconds'), 'steps': [
                 {'step': x['name'], 'seconds': x['seconds'] or 0.0,
                  'cached': x['cached']} for x in s]}
    heavy = [s for s in m.get('steps', []) if (s['seconds'] or 0) >= 1.0]
    return {k: m.get(k) for k in ('tag', 'rc', 'mode', 'git_sha', 'infra_sha',
                                  'wall_seconds', 'image_id', 'image_size_bytes')} \
        | {'steps_over_1s': heavy}


def tests_from(summary_path):
    s = rj(summary_path)
    if not s:
        return None
    return {'totals': s['totals'], 'wall_seconds': s['wall_seconds'],
            'jobs': s.get('jobs'),
            'packages': {p['package']: {k: p[k] for k in
                         ('passed', 'failed', 'errors', 'skipped', 'rc', 'seconds')}
                         for p in s['packages']},
            'non_passing': [{'package': p['package'], 'id': c['id'],
                             'outcome': c['outcome'], 'msg': c['msg'][:200]}
                            for p in s['packages'] for c in p['cases']
                            if c['outcome'] != 'passed']}


def validate(d):
    v = rj(os.path.join(d, 'validation.json'), {})
    reps = [tests_from(f) for f in sorted(glob.glob(os.path.join(d, 'tests/rep*/junit/summary.json')))]
    plat = [platform(p) for p in sorted(glob.glob(os.path.join(d, 'platform/rep*')))]
    return {'result': v.get('result'), 'stages': v.get('stages'),
            'build_info': v.get('build_info'),
            'environment_checks': rj(os.path.join(d, 'environment/checks.json')),
            'test_reps': reps, 'platform_reps': plat}


def platform(d):
    r = kv(os.path.join(d, 'result.txt'))
    g = rj(os.path.join(d, 'graph_probe.json'), {})
    stats = []
    if os.path.exists(os.path.join(d, 'steady_stats.csv')):
        for row in csv.reader(open(os.path.join(d, 'steady_stats.csv'))):
            if row:
                stats.append({'cpu': row[0], 'mem': row[1],
                              'pids': row[2] if len(row) > 2 else None})
    hz = rj(os.path.join(d, 'healthz.json'), {})
    cmdv = open(os.path.join(d, 'cmd_vel_info.txt')).read() \
        if os.path.exists(os.path.join(d, 'cmd_vel_info.txt')) else ''
    pubs = re.search(r'Publisher count: (\d+)', cmdv)
    node = re.search(r'Endpoint type: PUBLISHER', cmdv) and \
        re.search(r'Node name: (\S+)', cmdv)
    ctrl = open(os.path.join(d, 'controllers.txt')).read() \
        if os.path.exists(os.path.join(d, 'controllers.txt')) else ''
    return {'run': os.path.basename(d), **r,
            'healthz': {k: hz.get(k) for k in ('status', 'lifecycle', 'health',
                                               'missing', 'degraded_by')},
            'cmd_vel_publishers': int(pubs.group(1)) if pubs else None,
            'cmd_vel_publisher_node': node.group(1) if node else None,
            'controllers': [ln.split() for ln in ctrl.splitlines() if ln.strip()],
            'graph': {k: g.get(k) for k in ('rtf', 'topic_count', 'rates_hz',
                                            'tf_can_transform')}
            | {'node_count': len(g.get('nodes', []))},
            'steady_stats': stats,
            'listening': open(os.path.join(d, 'listening.txt')).read().split()
            if os.path.exists(os.path.join(d, 'listening.txt')) else None,
            'ws_probe': rj(os.path.join(d, 'ws_probe.json')),
            'nav_smoke': rj(os.path.join(d, 'nav_smoke.json'))}


def boot_probe(d):
    rows = list(csv.DictReader(open(os.path.join(d, 'boots.csv'))))
    return {'boots': rows,
            'by_image': {img: {'boots': sum(r['image'] == img for r in rows),
                               'all_active': sum(r['image'] == img and r['all_active'] == 'yes'
                                                 for r in rows)}
                         for img in sorted({r['image'] for r in rows})},
            'by_order': {o: {'boots': sum(r['ogre_t'] == o for r in rows),
                             'all_active': sum(r['ogre_t'] == o and r['all_active'] == 'yes'
                                               for r in rows)}
                         for o in sorted({r['ogre_t'] for r in rows})}}


def contention(d):
    return {'containers': [tests_from(f) for f in
                           sorted(glob.glob(os.path.join(d, 'c*/junit/summary.json')))],
            'peak_load1': max((float(ln.split()[1]) for ln in
                               open(os.path.join(d, 'loadavg.txt')) if ln.strip()),
                              default=None)}


def regression(d):
    return rj(os.path.join(d, 'regression.json'), [])


def environment(d):
    """A validate run's preflight/ (docker + host), plus host/inventory.txt."""
    pre = os.path.join(d, 'preflight')
    info = rj(os.path.join(pre, 'docker_info.json'), {}) or {}
    docker_txt = open(os.path.join(pre, 'docker.txt')).read() \
        if os.path.exists(os.path.join(pre, 'docker.txt')) else ''
    versions = {
        'client': re.search(r'Client:.*?Version:\s+(\S+)', docker_txt, re.S),
        'server': re.search(r'Server:.*?Version:\s+(\S+)', docker_txt, re.S),
        'compose': re.search(r'Docker Compose version (\S+)', docker_txt),
        'buildx': re.search(r'buildx (v\S+)', docker_txt)}
    inv = {}
    inv_path = os.path.join(os.path.dirname(os.path.dirname(d)), 'host', 'inventory.txt')
    if os.path.exists(inv_path):
        for line in open(inv_path):
            k, _, v = line.rstrip('\n').partition('=')
            inv[k] = v
    return {'docker': {k: (m.group(1) if m else None) for k, m in versions.items()},
            'daemon': {k: info.get(k) for k in (
                'ServerVersion', 'Driver', 'DriverStatus', 'CgroupDriver',
                'CgroupVersion', 'NCPU', 'MemTotal', 'KernelVersion',
                'OperatingSystem', 'DockerRootDir', 'SecurityOptions')}
            | {'Runtimes': sorted((info.get('Runtimes') or {}).keys())},
            'host_inventory': inv}


def main():
    index, out = rj(sys.argv[1]), sys.argv[2]
    root = index['root']
    os.makedirs(out, exist_ok=True)
    handlers = {'build': build, 'validate': validate, 'platform': platform,
                'boot_probe': boot_probe, 'contention': contention,
                'regression': regression, 'environment': environment,
                'host_tests': lambda d: tests_from(os.path.join(d, 'junit/summary.json')),
                'repeat': lambda d: open(d).read().strip() if os.path.isfile(d) else None,
                'determinism': lambda d: rj(os.path.join(d, 'determinism.json')),
                'failure': lambda d: {'context': rj(os.path.join(d, 'context.json')),
                                      'files': sorted(os.listdir(d)) if os.path.isdir(d) else []}}
    grouped = {}
    for run in index['runs']:
        path = os.path.join(root, run['path'])
        try:
            data = handlers[run['kind']](path)
        except Exception as exc:  # noqa: BLE001
            data = {'error': f'{type(exc).__name__}: {exc}'}
        grouped.setdefault(run['file'], []).append(
            {'label': run['label'], 'kind': run['kind'], 'path': run['path'],
             'note': run.get('note', ''), 'data': data})
    for name, rows in grouped.items():
        with open(os.path.join(out, name), 'w') as fh:
            json.dump(rows, fh, indent=1, sort_keys=False)
        print(f'{name}: {len(rows)} runs')


if __name__ == '__main__':
    main()
